### ISSUE TITLE
New navigation - event tracking

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/navigation#129] opened 2020-10-08 16:51 UTC
We'll need to implement event tracking in order to understand if merchants are using the new navigation and if they're managing their store effectively. Adding a global prop to any event identifying the nav that's being used seems to be the best option (similar to what we have with the `host` prop).

**Comment by pmcpinto** [comment] 2020-10-08 16:52
@timmyc what can be the best way to identify if the eComm users are using the new nav or in wp-admin once we have the new nav implemented and calypsoify removed?

**Comment by psealock** [comment] 2020-10-12 02:19
This is a duplicate of https://github.com/woocommerce/woocommerce-admin/issues/5332 so I'll close this out.

>what can be the best way to identify if the eComm users are using the new nav or in wp-admin once we have the new nav implemented and calypsoify removed?

By tying into the page view event and adding an `isNewNavigation` property (or something) we can query for users on eComm plan AND have the new property in page views. 

I assume this means the new Navigation is opt-in for eCommerce users? If we remove Calypsoify and replace it with Navigation for ALL eCommerce users the new Navigation experience will be turned on for all WC pages so users won't be using the wp-admin sidebar when viewing WooCommerce pages. Am I understanding correctly?

**Closed by psealock** 2020-10-12 02:19 UTC

**Comment by pmcpinto** [comment] 2020-10-12 09:48
> I assume this means the new Navigation is opt-in for eCommerce users? If we remove Calypsoify and replace it with Navigation for ALL eCommerce users the new Navigation experience will be turned on for all WC pages so users won't be using the wp-admin sidebar when viewing WooCommerce pages. Am I understanding correctly?

@psealock yes, however during the first weeks we should give them the option to disable the new nav and use wpadmin: https://github.com/woocommerce/woocommerce-admin/issues/5333
